import product01 from './assets/MakeAWay.jpg';


export const PRODUCTS = [
    {
        id: 1,
        productName: "Make a Way",
        price: 9.99,
        beatImage: product01,
        bpm: 145,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 2,
        productName: "MustardnMacSauce",
        price: 9.99,
        beatImage: product02,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 3,
        productName: "Looking Back",
        price: 9.99,
        beatImage: product03,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 4,
        productName: "Tilted Towers",
        price: 9.99,
        beatImage: product04,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 5,
        productName: "BLUFF",
        price: 9.99,
        beatImage: product05,
        bpm: 138,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 6,
        productName: "Relish Parts",
        price: 9.99,
        beatImage: product06,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 7,
        productName: "ProfessorX",
        price: 9.99,
        beatImage: product07,
        bpm: 134,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 8,
        productName: "Date Night",
        price: 9.99,
        beatImage: product08,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 9,
        productName: "Atrocity",
        price: 9.99,
        beatImage: product09,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 10,
        productName: "Alone Time",
        price: 9.99,
        beatImage: product10,
        bpm: 165,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 11,
        productName: "Bentley Beats",
        price: 9.99,
        beatImage: product11,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 12,
        productName: "thank the stars",
        price: 9.99,
        beatImage: product12,
        bpm: 145,
        artist: "SWOOSHiNAIRE",
    },
    {
        id: 13,
        productName: "forestfires",
        price: 9.99,
        beatImage: product13,
        bpm: 140,
        artist: "SWOOSHiNAIRE",
    },
]